package br.com.fiap.entity;

public enum Genero {
	MASCULINO, FEMININO, TRANSHOMEM, TRANSMULHER, TRAVESTI,TRANSGENERO, HOMEM_TRANSSEXUAL,MULHER_TRANSSEXUAL, PESSOA_TRANSSEXUAL, MULHER_TRANS,HOMEM_TRANS,NEUTRO,SEM_GENERO,CROSS_GENDER,OUTRO;
}
